id: I63732FE6
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-29T16:49:42+00:00'
last_modified: '2022-06-07T12:39:15.493148+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W22170
  title: ཐུའུ་བཀྭན་ཆོས་ཀྱི་ཉི་མའི་རྟོགས་བརྗོད་པདྨ་དཀར་པོ
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    59DA:
      image_group_id: I1GS105510
      title: ''
      total_pages: 624
      order: 1
      base_file: 59DA.txt
    DEE3:
      image_group_id: I1GS105511
      title: ''
      total_pages: 558
      order: 2
      base_file: DEE3.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
