id: P000683
initial_creation_type: ocr
created_at: 29/03/2020
last_modified_at: 24/11/2021
source_metadata:
  id: bdr:W22170
  title: ཐུའུ་བཀྭན་ཆོས་ཀྱི་ཉི་མའི་རྟོགས་བརྗོད་པདྨ་དཀར་པོ
  author: ''
  volumes:
    d79dee6a0142400d9c436bf265839cd9:
      image_group_id: I1GS105510
      title: ''
      volume_number: 1
      total_pages: 624
      base_file: v001.txt
    5bef9b4dcf664fbeb5f2f883ef37dbb9:
      image_group_id: I1GS105511
      title: ''
      volume_number: 2
      total_pages: 558
      base_file: v002.txt
